server:
  port: 8081

spring:
  application:
    name: check-in-service

  datasource:
    url: ${POSTGRES.DB.URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES.USER}
    password: ${POSTGRES.PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA.MAIL.SENDER.EMAIL}
    password: ${JAVA.MAIL.SENDER.APP.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    enabled: ${KAFKA.ENABLED:false}
    bootstrap-servers: ${KAFKA.BOOTSTRAP.SERVERS:localhost:29092}
    groups:
      email-group: ${KAFKA.GROUPS.EMAILS:defaultEmailGroup}
      recording-service-group: ${KAFKA.GROUPS.RECORD:defaultRecordingServiceGroup}
    topics:
      emails-topic: ${KAFKA.TOPICS.EMAILS:emails}
      recording-service-topic: ${KAFKA.TOPICS.RECORD:notify-recording-service}


app:
  shift:
    max-duration: 10
  services:
    recording-service:
      name: recordingService
      listener-id: recordingServiceListener
      circuit-breaker-enabled: true
      url: ${RECORDING.SERVICE.URL:http://localhost:8090}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 80
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      recordingService:
        baseConfig: default

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.kafka.retrytopic: DEBUG
    com.abdul.checkinservice: DEBUG