server:
  port: 8081

spring:
  application:
    name: check-in-service

  datasource:
    url: ${POSTGRES.DB.URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES.USER}
    password: ${POSTGRES.PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA.MAIL.SENDER.EMAIL}
    password: ${JAVA.MAIL.SENDER.APP.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    enabled: ${KAFKA.ENABLED:false}
    bootstrap-servers: ${KAFKA.BOOTSTRAP.SERVERS:localhost:29092}
    groups:
      email-group: ${KAFKA.GROUPS.EMAILS:defaultEmailGroup}
      recording-service-group: ${KAFKA.GROUPS.RECORD:defaultRecordingServiceGroup}
    topics:
      emails-topic: ${KAFKA.TOPICS.EMAILS:emails}
      recording-service-topic: ${KAFKA.TOPICS.RECORD:notify-recording-service}


app:
  shift:
    max-duration: 10

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.kafka.retrytopic: DEBUG
    com.abdul.checkinservice: DEBUG
