server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: ${ADMIN.CLIENT.URL:http://localhost:9090}
  application:
    name: check-in-service
  datasource:
    url: ${POSTGRES.DB.URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES.USER}
    password: ${POSTGRES.PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${JPA.SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA.PROPERTIES.HIBERNATE.FORMAT_SQL:true}

  mail:
    host: ${JAVA.MAIL.HOST:smtp.gmail.com}
    port: ${JAVA.MAIL.PORT:587}
    username: ${JAVA.MAIL.SENDER.EMAIL}
    password: ${JAVA.MAIL.SENDER.APP.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    enabled: ${KAFKA.ENABLED:false}
    bootstrap-servers: ${KAFKA.BOOTSTRAP.SERVERS:localhost:29092}
    groups:
      email-group: ${KAFKA.GROUPS.EMAILS:defaultEmailGroup}
      recording-service-group: ${KAFKA.GROUPS.RECORD:defaultRecordingServiceGroup}
    topics:
      emails-topic: ${KAFKA.TOPICS.EMAILS:emails}
      recording-service-topic: ${KAFKA.TOPICS.RECORD:notify-recording-service}


app:
  shift:
    max-duration: 10
  services:
    recording-service:
      name: recordingService
      listener-id: recordingServiceListener
      circuit-breaker-enabled: ${RECORDING.SERVICE.CIRCUIT_BREAKER.ENABLED:true}
      url: ${RECORDING.SERVICE.URL:http://localhost:8090}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: ${CIRCUIT_BREAKER.SLIDING.WINDOW.SIZE:3}
        minimumNumberOfCalls: ${CIRCUIT_BREAKER.MINIMUM_NUMBER_OF_CALLS:3}
        failureRateThreshold: ${CIRCUIT_BREAKER.FAILURE_THRESHOLD:80}
        waitDurationInOpenState: ${CIRCUIT_BREAKER.WAIT_DURATION_IN_OPEN_STATE:10s}
        permittedNumberOfCallsInHalfOpenState: ${CIRCUIT_BREAKER.PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE:2}
        automaticTransitionFromOpenToHalfOpenEnabled: ${CIRCUIT_BREAKER.AUTOMATIC_TRANSITION_FROM_OPEN_TO_HALF_OPEN_ENABLED:true}

logging:
  file:
    name: logs/check-in-service.log
  level:
    org.springframework.kafka: INFO
    org.springframework.kafka.retrytopic: DEBUG
    com.abdul.checkinservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,logfile,metrics